# dubbo配置
dubbo:
  application:
    name: dubbo-springboot-gateway-consumer
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  consumer:
    filter: -exception
    # 超时时间
    timeout: 10000